#!/usr/bin/env bash
# Simple pomodoro timer.

set -euo pipefail

TIME_WORK=20m
TIME_BREAK=5m

function alarm() {
    local -r time="$(date '+%H:%M')"
    local -r message="${time} - ${1}"
    echo "${message}"
    notify-send "${message}"

    for run in {1..3}; do
        paplay alarm.mp3
    done
}

while true; do
    alarm 'Starting Work'
    sleep "${TIME_WORK}"

    alarm 'Starting Break'
    sleep "${TIME_BREAK}"
done

